language: python
python: "3.9"
dist: xenial

stages:
  - TEST
  - DEPLOY

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

jobs:
  include:
    - stage: TEST
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - behave
    - stage: DEPLOY
      script:
        - echo Deploying to PyPI...

before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry build
  - poetry config repositories.test-pypi https://test.pypi.org/legacy/
  - poetry config http-basic.test-pypi __token__ $TEST_PYPI_PASSWORD

deploy:
  provider: script 
  script: poetry publish -r test-pypi
  skip_cleanup: true
  on:
    all_branches: true
    repo: cosinato/picklerick
    tags: false
