language: python
python: "3.9"
dist: xenial

stages:
  - TEST
  - DEPLOY

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

jobs:
  include:
    - stage: TEST
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - behave
    - stage: DEPLOY
      script:
        - echo Deploying to PyPI...

before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config repositories.test-pypi https://test.pypi.org/legacy/
  - poetry build

deploy:
  provider: script 
  script: poetry publish -r test-pypi
  user: __token__
  password: $TEST_PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  on:
    all_branches: true
    condition: $TRAVIS_BUILD_STAGE_NAME = DEPLOY
    repo: cosinato/picklerick
    tags: false

#
